version: '3'

services:
  traefik:
    image: traefik:v1.7
    command: --docker
    ports:
      - 80:80
    networks:
      - proxy
      - internal
    labels:
      - "traefik.frontend.rule=Host:web.localhost"
      - "traefik.port=8080"
      - "traefik.docker.network=proxy"
    volumes:
      - ./traefik.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
  nginx:
    image: nginx:latest
    networks:
      - proxy
    labels: 
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:/static/"
      - "traefik.docker.network=proxy"
  influxdb:
    image: influxdb:1.7.7
    networks: 
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=localhost"
      - "traefik.port=8086"
      - "traefik.docker.network=proxy"
  chronograf:
    image: chronograf:1.7.12
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=chrono"
      - "traefik.frontend.rule=Host:chrono.localhost"
      - "traefik.docker.network=proxy"
      - "traefik.port=8888"
networks: 
  proxy:
    external: 
      name: proxy
  internal:
    external: false